### ISSUE TITLE
HackerNews importer aggressive network usage

### ISSUE THREAD

**Issue by IhostVlad** [reimagined/hacker-news-resolve#124]
Importing **only one** HackerNews story affects invoking more than 30000 tcp + udp packets, which is very redundant. Performing import is necessary when event structure had been changed. It's not very frequent operation while development, but non rare too.

For example, only resolving IP-address of HackerNews website by DNS performs hundred and hundred times repeatably. [import_hn.log](https://github.com/reimagined/hacker-news-resolve/files/1571168/import_hn.log).
In comparation, two minutes of 4K youtube video consumes only approximate 1900 tcp packets and works very well. [youtube.log](https://github.com/reimagined/hacker-news-resolve/files/1571283/youtube.log)

Issue faced on Ubuntu 16.04.1 LTS on VirtualBox 5.2.0, virtual network adapter is:
`82540EM Gigabit Ethernet Controller (pm pcix bus_master cap_list ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation, autonegotiation=on broadcast=yes driver=e1000 driverversion=7.3.21-k8-NAPI duplex=full ip=10.0.2.15 latency=64 link=yes mingnt=255 multicast=yes port=twisted pair speed=1Gbit/s)`

Most likely, that current importer implementation performs big traffic flood, which can be handled by physical adapter, but very much for virtual.

**Comment by superroma** [comment]
Vlad, don't waste time on optimizing this. The value of fixing this issue much less than the time you invested reporting it.
